/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Fri Nov  1 17:49:56 2019. */

#include "oven.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SetTarget_fields[2] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, SetTarget, targetTemp, targetTemp, 0),
    PB_LAST_FIELD
};

const pb_field_t ReflowPoint_fields[3] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, ReflowPoint, time, time, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, ReflowPoint, temp, time, 0),
    PB_LAST_FIELD
};

const pb_field_t ReflowCurve_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, ReflowCurve, reflowPoints, reflowPoints, &ReflowPoint_fields),
    PB_LAST_FIELD
};

const pb_field_t PIDTune_fields[4] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, PIDTune, p, p, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDTune, i, p, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDTune, d, i, 0),
    PB_LAST_FIELD
};

const pb_field_t OvenConfiguration_fields[3] = {
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , FIRST, OvenConfiguration, pidTune, pidTune, &PIDTune_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, OvenConfiguration, reflowCurve, pidTune, &ReflowCurve_fields),
    PB_LAST_FIELD
};

const pb_field_t OvenStatus_fields[6] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, OvenStatus, ovenTemp, ovenTemp, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, OvenStatus, ambientTemp, ovenTemp, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, OvenStatus, targetTemp, ambientTemp, 0),
    PB_FIELD(  4, UENUM   , OPTIONAL, STATIC  , OTHER, OvenStatus, ovenState, targetTemp, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, OvenStatus, outputPower, ovenState, 0),
    PB_LAST_FIELD
};

const pb_field_t TxMicro_fields[4] = {
    PB_FIELD(  1, INT64   , OPTIONAL, STATIC  , FIRST, TxMicro, timeStamp, timeStamp, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, TxMicro, ovenStatus, timeStamp, &OvenStatus_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, TxMicro, ovenConfiguration, ovenStatus, &OvenConfiguration_fields),
    PB_LAST_FIELD
};

const pb_field_t RxMicro_fields[4] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, RxMicro, target, target, &SetTarget_fields),
    PB_FIELD(  2, UENUM   , OPTIONAL, STATIC  , OTHER, RxMicro, ovenState, target, 0),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, RxMicro, ovenConfiguration, ovenState, &OvenConfiguration_fields),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ReflowCurve, reflowPoints[0]) < 65536 && pb_membersize(OvenConfiguration, pidTune) < 65536 && pb_membersize(OvenConfiguration, reflowCurve) < 65536 && pb_membersize(TxMicro, ovenStatus) < 65536 && pb_membersize(TxMicro, ovenConfiguration) < 65536 && pb_membersize(RxMicro, target) < 65536 && pb_membersize(RxMicro, ovenConfiguration) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_SetTarget_ReflowPoint_ReflowCurve_PIDTune_OvenConfiguration_OvenStatus_TxMicro_RxMicro)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for ReflowCurve.reflowPoints is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
